ublue-os/beyond

etc/dconf/db/local.d/01-ublue

Also cut out a bunch of bluefin opinions, more to come.

feat: switch to inter font

---

packages.json

feat: swap out gnome-terminal for gnome-console

---

etc/yafti.yml

Fixes #11 #5 and #6 
cc @marcoceppi I'm not sure if I can put the system:true in the section above to make this section less wordy.

feat: add loupe, snapshot, and web

---

README.md

docs: Add installation instructions to README

---

etc/yafti.yml

…and don't separate them into two sections. This also removes some apps I don't want to install. 😄

feat: Install all core apps as system

---

etc/yafti.yml

Lemme know if I did that right. Should fix #25.

feat: Move some apps to Utilities

---

usr/share/ublue-os/just/custom.just

fix: remove dock-from-dash

---

etc/dconf/db/local.d/01-ublue

feat: remove non-upstream window button layouts

---

etc/dconf/db/local.d/01-ublue

fix: remove unwanted dconf overrides

---

etc/dconf/db/local.d/01-ublue

This mirrors what I use and is fairly lightweight-feeling compared to the default GNOME dash

feat: update dash-to-dock settings

---

etc/distrobox/distrobox.conf
etc/distrobox/distrobox.ini

fix: remove distrobox config

---

etc/dconf/db/local.d/01-ublue

feat: set default dash configuration

---

etc/yafti.yml

feat: Add Extension Manager to utilities

---

etc/yafti.yml

Makes sense as a utility for someone who knows what they want

feat: Add Flatseal to optional utilities

---

etc/yafti.yml

feat: add boxes to utilities

---

etc/dconf/db/local.d/01-ublue

feat: Enable scale-monitor-framebuffer

---

etc/dconf/db/local.d/01-ublue

feat: Sort folders before files

---

packages.json

feat: remove GNOME Tweaks from default install

---

etc/dconf/db/local.d/01-ublue
usr/share/gnome-shell/extensions/activities-filled-pill@verdre/extension.js
usr/share/gnome-shell/extensions/activities-filled-pill@verdre/metadata.json
usr/share/gnome-shell/extensions/activities-filled-pill@verdre/stylesheet.css

Trialing it from https://gitlab.gnome.org/Teams/Design/os-mockups/-/issues/227

feat: Add and enable activities-filled-pill extension

---

usr/share/ublue-os/just/60-custom.just

Depends on the following PR landing:
https://github.com/ublue-os/config/pull/118

feat: Switch to new justfile system
